-- Customer table for QR-based shopping (Skip if already exists)
create table if not exists public."Customer" (
  id uuid default gen_random_uuid() not null,
  customer_name text not null,
  email text null,
  phone text null,
  qr_code text not null unique,
  created_at timestamp with time zone not null default now(),
  constraint Customer_pkey primary key (id),
  constraint Customer_qr_code_key unique (qr_code)
) tablespace pg_default;

-- Update Cart table to link with Customer (Skip if constraint already exists)
do $$ 
begin
  if not exists (
    select 1 from pg_constraint where conname = 'Cart_customer_id_fkey'
  ) then
    alter table public."Cart" 
    add constraint Cart_customer_id_fkey 
    foreign key (customer_id) 
    references "Customer" (id);
  end if;
end $$;

-- Create Session table to track active shopping sessions
create table if not exists public."ShoppingSession" (
  id bigint generated by default as identity not null,
  customer_id uuid not null,
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone null,
  is_active boolean default true,
  constraint ShoppingSession_pkey primary key (id),
  constraint ShoppingSession_customer_id_fkey foreign key (customer_id) references "Customer" (id)
) tablespace pg_default;

-- Disable RLS for testing (you can enable and add policies later)
alter table public."Customer" disable row level security;
alter table public."Cart" disable row level security;
alter table public."ShoppingSession" disable row level security;
